### ISSUE TITLE
License terms changed without even asking permission of contributors

### ISSUE THREAD

**Issue by SteveDaulton** [yonderbread/foss_audacity#20]
**Describe the bug**
My code contributions are licensed under GPLv2, or "GPLv2 or later".
You do NOT have my permission to impose license restrictions that go beyond GPL v2 restrictions.

**To Reproduce**
See here: https://github.com/yonderbread/foss_audacity/commit/8287370aba1a27a29aca4032a4e2d5ef2cc729bf

**Expected behavior**
The GPL v2 license  terms should be allowed without restriction.
If you wish to extend the license terms, you should make all reasonable efforts to contact the contributors BEFORE changing the license terms.

**Resolution**
Revert commits 8287370aba1a2 and 7a811d5af6f8a9
or remove all of my contributions from this repository.

**Comment by SteveDaulton** [comment]
See GitHub Terms of Service: https://docs.github.com/en/github/site-policy/github-terms-of-service#3-ownership-of-content-right-to-post-and-license-grants
Specifically:

**3. Ownership of Content, Right to Post, and License Grants**

You retain ownership of and responsibility for Your Content. If you're posting anything you did not create yourself or do not own the rights to, you agree that you are responsible for any Content you post; that you will only submit Content that you have the right to post; **_and that you will fully comply with any third party licenses relating to Content you post._**

**Comment by yonderbread** [comment]
I apologize for this, reverted back to v2.
https://github.com/yonderbread/foss_audacity/commit/e6a65ef36a9191f54e0d83f3b74d579fe4513872
https://github.com/yonderbread/foss_audacity/commit/24bf32653fef123d8533553fe7f1bc0563dc4f05
https://github.com/yonderbread/foss_audacity/pull/21
