### ISSUE TITLE
Update License

### ISSUE THREAD

**Issue by yonderbread** [yonderbread/foss_audacity#4]
How would you all feel if I were to update the license to GPL3?

**Comment by FrostKnight** [comment]
I would recommend updating it to gpl3, and btw, you should make your repo public and have the word spread for people to support your cause instead of the current one.  I myself don't need audacity currently, but adding yandex and google stuff is just wrong... very much so.

**Comment by dertuxmalwieder** [comment]
Wouldn't a license change require all contributors to agree?

**Comment by yonderbread** [comment]
> I would recommend updating it to gpl3, and btw, you should make your repo public and have the word spread for people to support your cause instead of the current one.  I myself don't need audacity currently, but adding yandex and google stuff is just wrong... very much so.

Alright, well lets see what other people think first. Also what do you mean by make the repo public? Isn't it already public?

**Comment by yonderbread** [comment]
> Wouldn't a license change require all contributors to agree?

I'm not sure, I just think it'd be a good idea to update to the latest version of the license.

**Comment by DaVince** [comment]
> Wouldn't a license change require all contributors to agree?

Normally, yes. But this is moving from the GPL to a later version of the GPL, and the license itself has this clause:

> Each version is given a distinguishing version number.  If the Program
> specifies a version number of this License which applies to it and **"any**
> **later version"**, you have the option of following the terms and conditions
> either of that version or of any later version published by the Free
> Software Foundation.

What I'm more concerned about is that this fork kinda popped up out of nowhere, but is there any coordination behind it? Of course you can fork a big successful piece of software but being succesful at maintaining the fork is a different issue altogether. I'd rather trust the Audacity devs to be able to take the backlash into serious consideration until they've made their decision on the whole thing, before hastily deciding on devising a whole new fork.

**Comment by yonderbread** [comment]
I'm honestly cool with whatever the community wants to do, I haven't maintained a project based on something so large before. I honestly just kinda wanted to keep our fork at the same version and just add new features onto it.

**Comment by yzziizzy** [comment]
> What I'm more concerned about is that this fork kinda popped up out of nowhere, but is there any coordination behind it? Of course you can fork a big successful piece of software but being succesful at maintaining the fork is a different issue altogether. I'd rather trust the Audacity devs to be able to take the backlash into serious consideration until they've made their decision on the whole thing, before hastily deciding on devising a whole new fork.
> 
> Sorry, I'm trailing off. You're entirely free to do whatever. :)

I just hopped behind the first guy to click "fork" and volunteered to add "return NULL;" at the top of all the telemetry fns should the main project take the road of insanity. It's mostly about showing support for a Google/Yandex-free fork, be that this one or whichever one becomes the primary fork.

**Comment by FrostKnight** [comment]
Seems like the issue is fixed... for now. They plan to drop google/yandex for telemetry...

Keep watch though in case... ;)

**Comment by yonderbread** [comment]
No matter what happens I refuse to merge any following commits into our fork, the upstream repo has been soiled.

**Comment by FrostKnight** [comment]
For all I know, that might be wise... this time they stopped being dicks, next time, who knows...

**Comment by yonderbread** [comment]
> For all I know, that might be wise... this time they stopped being dicks, next time, who knows...

They've broken our trust, I have no respect for the new Audacity team.

**Comment by FrostKnight** [comment]
@yonderbread "They've broken our trust, I have no respect for the new Audacity team."
That was actually my point...
Sooner or later, they will do something even worse that will be even more problematic.  So yeah, making a fork is pretty good idea, depending on how its implemented.  I am hopeful it will be better than the original. Like how libreoffice kicked openoffice's ass. ;)

**Comment by FrostKnight** [comment]
And as you said, and as I expected, they have gotten worse... 

CLA agreements... :(

...
